name: Article-Functional-Tests

on:
  push:
    tags:
      - '!refs/tags/*'
    branches:
      - '*'

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
     #Setup Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install software
        run: sudo apt-get install -y firefox
      - name: Install the necessary packages
        run: pip install requests webdriver-manager selenium

      - name: Install requirements
        # Устанавливаем зависимости
        run: pip install -r requirements.txt

      - name: Migrations
        run: |
          python manage.py makemigrations
          python manage.py migrate

      - name: Run functional tests
        run: python manage.py test functional_tests.guides_tests.test_article
        env:
          HEADLESS_DRIVER: True

      - name: Upload pytest test results
        uses: actions/upload-artifact@v3
        with:
          name: logs
          path: logs
        if: ${{ always() }}