name: Init

on:
  workflow_call:
    inputs:
      tests-path:
        required: true
        type: string

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - uses: actions/cache@v3
        with:
          path: ~/.cache/firefox
          key: ${{ hashFiles('setup.py') }}-${{ hashFiles('firefox') }}

      - name: Install software
        run: sudo apt-get install -y firefox

      - name: Update pip
        run: python -m pip install --upgrade pip
      - name: Install the necessary packages
        run: pip install requests webdriver-manager selenium

      - name: Cache requirements
        id: cache-requirements
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ hashFiles('setup.py') }}-${{ hashFiles('requirements.txt') }}
          restore-keys: ${{ hashFiles('setup.py') }}-

      - if: ${{ steps.cache-requirements.outputs.cache-hit != 'true' }}
        name: Install requirements
        run: pip install --upgrade --upgrade-strategy eager -r requirements.txt

      - name: Migrations
        run: |
          python manage.py makemigrations
          python manage.py migrate

      - name: Run functional tests
        run: python manage.py test functional_tests.${{ inputs.tests-path }}
        env:
          HEADLESS_DRIVER: True

      - name: Upload pytest test results
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.tests-path }}_logs
          path: logs
        if: ${{ failure() }}
