name: Init-with-firefox-container

on:
  workflow_call:
    inputs:
      tests-path:
        required: true
        type: string

jobs:
  init:
    runs-on: ubuntu-latest

#    container:
#      image: python:3.10

    services:
      selenium:
        image: selenium/standalone-firefox:latest

    steps:
      - name: Check out this repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: 'requirements.txt'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests webdriver-manager selenium
          pip install -r requirements.txt
#          pip install --upgrade --upgrade-strategy eager -r requirements.txt

#      - name: Update pip
#        run: python -m pip install --upgrade pip
#
#
#      - name: Install the necessary packages
#        run: pip install requests webdriver-manager selenium
#
#      - name: Install requirements
#        run: pip install --upgrade --upgrade-strategy eager -r requirements.txt

      - name: Migrations
        run: |
          python manage.py makemigrations
          python manage.py migrate

      - name: Run functional tests
#        run : echo "python manage.py test functional_tests.${{ inputs.tests-path }}"
        run: python manage.py test functional_tests.${{ inputs.tests-path }}
        env:
          HEADLESS_DRIVER: True

      - name: Upload pytest test results
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.tests-path }}_logs
          path: logs
        if: ${{ failure() }}
