name: Unit-tests

on:
  push:
    tags:
      - '!refs/tags/*'
    branches:
      - '*'

jobs:
  run_tests:
    runs-on: [ubuntu-latest]
    steps:
      # Чекаутим код
      - uses: actions/checkout@master

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.10'
          architecture: 'x64'

      - name: Install requirements
        # Устанавливаем зависимости
        run: pip install -r requirements.txt

      - name: View files in the container
        run: ls -la

      - name: Migrations
        run: |
          python manage.py makemigrations
          python manage.py migrate

      - name: Run tests
        run: python manage.py test guides.tests